name: deploy

on: [push]

jobs:
  deploy-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Github repository
        uses: shawnbot/npm-publish-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
